export type DashboardLang = 'zh' | 'en';

export const DASHBOARD_LANG_STORAGE_KEY = 'restaurantiq.dashboard.lang';

export const dashboardCopy = {
  zh: {
    common: {
      dashboard: '总览',
      analysis: '分析中心',
      agentStudio: 'Agent 管理',
      settings: '设置',
      account: '账户',
      socialRadar: '社媒雷达',
      delivery: '订单中心',
      menuManagement: '菜单管理',
      opsCopilot: '经营 Copilot',
      signIn: '登录',
      startTrial: '开始试用',
      runAnalysis: '运行分析',
      mockMode: 'Mock 模式',
      authNotConfigured: '认证未配置',
      save: '保存',
      cancel: '取消',
      close: '关闭',
      testing: '测试中…',
      testConnection: '测试连接',
      viewSetup: '查看说明',
      loading: '加载中…',
      submitting: '提交中…',
      yes: '是',
      no: '否',
      languageToggle: 'EN',
      languageAria: '切换语言',
      sourceMock: '模拟数据',
      sourceLive: '实时',
      sourceFallback: '回退(模拟)'
    },
    shell: {
      title: 'Restaurant IQ',
      subtitle: '运营控制中心',
      mobileMenuClose: '关闭菜单',
      internalStudio: '内部 Agent Studio'
    },
    dashboardPage: {
      title: '总览',
      description: 'Restaurant IQ 控制台总览：查看融合信号、执行建议并监控回滚窗口。',
      badge: '实时运营',
      updatedPrefix: '更新时间',
      refresh: '刷新',
      refreshToast: '总览数据已刷新。',
      recommendedActions: '推荐动作',
      recommendedDesc: '按影响力 × 紧急度 × 可行性排序的优先动作。',
      openAnalysis: '打开分析中心',
      openAnalysisToast: '前往 Analysis 页面使用完整分析与执行控制。'
    },
    dashboardInsights: {
      title: '运营健康总览',
      description: '基于真实解析数据，展示经营健康度、月度趋势、平台分布与优先动作。',
      healthScore: '运营健康度',
      healthIssue: '主要问题',
      healthStrength: '优势项',
      monthlyTrend: '月度趋势',
      platformDistribution: '平台订单分布',
      platformNoData: '当前上传数据未包含平台拆分，后续接入外卖平台后可显示。',
      topRecommendation: '当前优先建议',
      noRecommendation: '当前还没有可执行建议，请先运行分析。',
      recommendationOutcome: '预期结果',
      recommendationConfidence: '置信度',
      recommendationImpact: '影响力',
      recommendationHumanReview: '需人工确认',
      recommendationReady: '可进入执行预览',
      whyTitle: '为什么推荐这个动作？',
      whyFinding: '发现问题',
      whyEvidence: '数据支撑',
      whyBenchmark: '行业对比',
      impactTitle: '执行后会有什么效果？',
      impactBenefit: '预期收益',
      impactFinancial: '财务影响',
      impactTimeline: '见效时间',
      stepsTitle: '执行步骤',
      riskTitle: '风险控制',
      stopLoss: '止损条件',
      rollbackPlan: '回滚方案',
    },
    analysisSummary: {
      title: '融合分析摘要',
      description: 'Agent A/B/C 信号合并输出，并对建议进行安全执行评分。',
      sourceLabels: { mock: '模拟数据', live: '实时', fallback: '回退数据' },
      fallbackWarning: '实时分析不可用，当前显示模拟建议。'
    },
    recommendation: {
      executePreview: '执行预览',
      details: '详情',
      hide: '收起',
      urgency: '紧急度',
      feasibility: '可行性',
      confidence: '置信度',
      expectedOutcome: '预期结果',
      highRiskNotice: '高风险动作建议启用经理确认后再开启自动执行。',
      rollbackExpired: '已过期',
      rollbackLabel: '回滚',
      rollbackWindow: '回滚窗口',
      statuses: {
        idle: '未执行',
        pending: '排队中',
        executing: '执行中',
        completed: '已完成',
        failed: '失败',
        rolled_back: '已回滚'
      },
      risk: {
        low: '低风险',
        medium: '中风险',
        high: '高风险'
      }
    },
    executionPreview: {
      title: '执行预览',
      rollbackAvailable: '支持回滚',
      slideLabel: '滑动确认执行该建议',
      slideConfirm: '已提交执行',
      cancel: '取消',
      errorFallback: '执行失败'
    },
    executionLogs: {
      title: '执行日志',
      empty: '还没有执行记录。运行分析并执行建议后，这里会显示日志。'
    },
    analysisPage: {
      title: '分析中心',
      description: 'Fuse Agent A/B/C signals, rank recommendations, preview execution, and apply guarded actions with swipe confirmation.',
      badge: 'Interactive',
      hideInputPanel: 'Hide Input Panel',
      showInputPanel: 'Show Input Panel',
      inputTitle: 'Analysis Input Panel',
      inputDescription: 'Restaurant profile + source status. Run analysis to refresh recommendations.',
      runAnalysis: 'Run Analysis',
      runningAnalysis: 'Running…',
      analysisDoneToast: 'Analysis run completed.',
      fieldCuisine: 'Cuisine',
      fieldLocation: 'City',
      fieldCapacity: 'Capacity',
      fieldPriceBand: 'Price band',
      fieldHours: 'Hours',
      agentSources: 'Agent Sources',
      sortTitle: 'Recommendations',
      sortDesc: 'Sort by impact, urgency, or blended score.',
      sortComposite: 'Composite',
      sortImpact: 'Impact',
      sortUrgency: 'Urgency',
      noRecommendations: 'No recommendations yet. Adjust inputs and run analysis.',
      executeToastPrefix: 'Execution requested: ',
      rollbackToastPrefix: 'Rollback submitted: ',
      businessDiscovery: 'Business Discovery & Analysis Entry',
      businessDiscoveryDesc: 'Enter an address, select a target business, then run analysis. The system pulls Google/Yelp reviews, images, and area signals to output executable actions.',
      searchBusiness: 'Search business',
      searching: 'Searching…',
      analyzeSelected: 'Analyze selected',
      analyzing: 'Analyzing…',
      compare: 'Compare',
      comparing: 'Comparing…',
      opsUpload: 'Operations Upload (Optional Supplement)',
      opsUploadDesc: 'If POS/delivery integrations are not connected yet, upload files as supplemental Agent-A inputs.',
      uploadDocument: 'Upload',
      uploading: 'Uploading…',
      expandUploaded: 'Expand uploaded',
      collapseUploaded: 'Collapse uploaded',
      clear: 'Clear',
      runOpsAnalysis: 'Run Ops Data Analysis',
      submitting: 'Submitting…',
      parsedDatasets: 'Parsed datasets',
      healthScore: 'Health score',
      p0Tasks: 'P0 tasks',
      discountRate: 'Discount rate',
      parsingCleaning: 'Parsing & cleaning results',
      businessInsights: 'High-quality business insights',
      executableRecommendations: 'Executable recommendations (prioritized)',
      businessIntel: 'Business Intelligence Deep-Dive',
      googleRating: 'Google Rating',
      yelpRating: 'Yelp Rating',
      population: 'Population',
      medianIncome: 'Median income',
      areaSignals: 'Area Signals',
      city: 'City',
      weather: 'Weather',
      traffic: 'Traffic',
      businessMix: 'Business mix',
      source: 'Source',
      executiveSummary: 'Executive summary',
      topRecommendation: 'Top recommendation',
      deepReviewAnalytics: 'Deep review analytics',
      totalReviews: 'Total reviews',
      positive: 'Positive',
      negative: 'Negative',
      mixed: 'Mixed',
      competitorAnalysis: 'Precise competitor analysis',
      scenarioCompetitors: 'Scenario competitors',
      consumerProfile: 'Consumer profile & platform intelligence',
      storeComparison: 'Store comparison (your store vs target)',
      yourRevenue: 'Your revenue',
      yourAov: 'Your AOV',
      targetGoogleRating: 'Target Google rating',
      targetYelpRating: 'Target Yelp rating',
      current: 'Current',
      benchmark: 'Benchmark',
      actions: 'Actions',
      googlePhotos: 'Google Photos',
      yelpPhotos: 'Yelp Photos',
      noPhotos: 'No photos loaded.',
      noReviews: 'No reviews loaded.',
    },
    swipe: {
      defaultLabel: '滑动确认执行',
      defaultConfirm: '已确认',
      submitting: '提交中…',
      aria: '滑动确认'
    },
    settingsPage: {
      title: '设置中心',
      description: '管理餐厅档案、Agent 开关、执行策略、模型路由与集成健康状态。',
      badge: '本地持久化',
      restoreDefaults: '恢复默认值',
      saveAll: '保存全部',
      savingAll: '保存中…',
      saveToast: '配置已保存',
      restoreToast: '已恢复默认配置',
      testedToastPrefix: '已测试'
    },
    settings: {
      restaurantProfile: '餐厅基础配置',
      saveProfile: '保存配置',
      profileSaved: '餐厅配置已保存',
      fields: {
        restaurantName: '餐厅名称', cuisine: '菜系类型', address: '地址', city: '城市', zip: 'ZIP', capacity: '容量（座位数）', priceBand: '价格带', hours: '营业时间（JSON/文本）'
      },
      agentPanel: {
        title: 'Agent 开关与刷新策略',
        refreshFrequency: '刷新频率',
        severityThreshold: '异常阈值',
        agentA: 'Agent A · 运营数据',
        agentB: 'Agent B · 社媒与口碑',
        agentC: 'Agent C · 宏观因子',
        agentDesc: '启用该 Agent 的数据采集与信号评分。'
      },
      executionPolicy: {
        title: '执行策略',
        allowAutoExecution: '允许自动执行',
        allowAutoExecutionDesc: '默认关闭，仅开启低风险自动化动作。',
        requireSecondConfirm: '高风险二次确认',
        requireSecondConfirmDesc: '高风险任务需经理确认后执行。',
        rollbackWindow: '回滚窗口',
        maxPriceAdjustment: '最大单次价格调整 (%)',
        blacklistCategories: '黑名单类目'
      },
      modelRouting: {
        title: '模型路由策略',
        simpleTasks: '简单任务模型',
        analysisTasks: '分析任务模型',
        criticalDecisions: '关键决策模型',
        tokenBudget: '每日 Token 预算',
        estimatedCost: '估算成本（mock）',
        preset: '策略预设',
        optimizationMode: '优化模式',
        qualityFirst: '质量优先',
        costFirst: '成本优先',
        presetCost: '成本优先',
        presetQuality: '质量优先'
      },
      integrationStatus: {
        title: 'API 集成状态',
        setupGuideTitle: '集成配置说明',
        lastTested: '最后测试时间',
        never: '从未',
        statuses: { connected: '已连接', missing: '未配置', error: '错误' }
      }
    },
    accountPage: {
      title: '账户中心',
      description: '订阅信息、组织信息、团队成员权限与 API 配置状态。',
      badge: '工作区',
      mockBadge: 'Mock',
      mockDescription: 'Mock 模式账户视图。认证关闭时展示占位数据。',
      currentUser: '当前用户'
    },
    account: {
      subscription: '订阅信息',
      currentPlan: '当前计划',
      upgrade: '升级计划',
      upgradeToast: 'Mock 升级流程：后续接入 Billing/Checkout。',
      teamMembers: '团队成员',
      teamDesc: '邀请经理与员工并配置角色权限（mock 流程）。',
      inviteMember: '邀请成员',
      inviteTitle: '邀请团队成员',
      sendInvite: '发送邀请',
      inviteSentPrefix: '邀请已发送至',
      orgTitle: '组织信息',
      orgName: '组织名称',
      role: '角色',
      rolePlaceholder: '店主',
      roleLabels: { Owner: '店主', Manager: '经理', Staff: '员工' },
      demoUser: '演示用户',
      orgFootnote: '成员权限面板为占位版本，后续可扩展为组织级 RBAC。',
      securityTitle: '安全与 API 配置状态',
      securityNote: '不要在前端保存 secret。OpenAI/Yelp/Google Maps 等服务端密钥必须放在 .env.local 并仅由 API Route 使用。',
      configured: '已配置',
      missing: '未配置',
      subscriptionStats: { plan: '计划', analysisUsage: '分析用量', executionUsage: '执行用量' },
      memberStatus: { active: '已激活', invited: '已邀请' },
      mockUpgradeToast: 'Mock 升级流程。'
    },
    forms: {
      validationRequired: '必填',
      validationEmail: '邮箱格式错误',
      inviteName: '姓名',
      inviteEmail: '邮箱',
      inviteRole: '角色'
    },
    billingAccess: {
      title: '计费 / 权限控制演示',
      authDisabledTitle: '认证已关闭',
      authDisabledBody: '当前环境启用了 Mock 模式，或未配置 Clerk，因此计费权限检查不会生效。',
      description: '演示 Clerk Plans 与 Features 的两种访问控制方式：`auth().has()` 与 `<Protect />`。',
      planCheck: '服务端检查：计划 (auth().has)',
      featureCheck: '服务端检查：功能 (auth().has)',
      hasPro: '已开通 Pro',
      noPro: '未开通 Pro',
      featureOn: '功能已启用',
      featureOff: '功能未启用',
      proGranted: '当前用户可以访问 Pro 专属内容。',
      proDenied: '当前用户还不能访问 Pro 专属内容。',
      socialReplyGranted: '当前组织已启用 AI 社交回复能力。',
      socialReplyDenied: '当前组织还未获得 AI 社交回复能力。',
      proFallbackTitle: '<Protect plan="pro" /> 回退内容',
      proFallbackBody: '只有 Pro 计划组织可以看到这个受保护模块。',
      proProtectedTitle: 'Pro 计划受保护模块',
      proProtectedBody: '仅当 Clerk 授予 `plan=pro` 时可见。',
      featureFallbackTitle: '<Protect feature="social_ai_reply" /> 回退内容',
      featureFallbackBody: '在 Clerk Billing 中启用 `social_ai_reply` 功能后，才能解锁 AI 社交回复工作流。',
      featureProtectedTitle: '功能受保护模块：AI 社交回复',
      featureProtectedBody: '这个模块演示了如何为 Social Media Radar 的 AI 回复能力做 feature gating。'
    }
  },
  en: {
    common: {
      dashboard: 'Dashboard', analysis: 'Analysis', agentStudio: 'Agent Studio', settings: 'Settings', account: 'Account', socialRadar: 'Social Radar', delivery: 'Order Center', menuManagement: 'Menu Management', opsCopilot: 'Ops Copilot', signIn: 'Sign in', startTrial: 'Start Trial', runAnalysis: 'Run Analysis', mockMode: 'Mock Mode', authNotConfigured: 'Auth Not Configured', save: 'Save', cancel: 'Cancel', close: 'Close', testing: 'Testing…', testConnection: 'Test Connection', viewSetup: 'View Setup', loading: 'Loading…', submitting: 'Submitting…', yes: 'Yes', no: 'No', languageToggle: '中', languageAria: 'Toggle language', sourceMock: 'Mock', sourceLive: 'Live', sourceFallback: 'Fallback'
    },
    shell: { title: 'Restaurant IQ', subtitle: 'Ops Control Center', mobileMenuClose: 'Close menu', internalStudio: 'Internal Agent Studio' },
    dashboardPage: { title: 'Dashboard', description: 'Restaurant IQ command center. Review fused signals, execute recommendations, and monitor rollback windows.', badge: 'Live Ops', updatedPrefix: 'Updated', refresh: 'Refresh', refreshToast: 'Dashboard data refreshed.', recommendedActions: 'Recommended Actions', recommendedDesc: 'Top actions ranked by impact × urgency × feasibility.', openAnalysis: 'Open Analysis', openAnalysisToast: 'Go to Analysis for full controls and execution flow.' },
    dashboardInsights: {
      title: 'Operational Health Snapshot',
      description: 'Shows business health, monthly trend, channel mix, and the next best action from parsed operating data.',
      healthScore: 'Operational Health Score',
      healthIssue: 'Primary issue',
      healthStrength: 'Strength',
      monthlyTrend: 'Revenue Trend',
      platformDistribution: 'Platform Order Mix',
      platformNoData: 'No platform split available yet. Connect delivery platforms to populate this section.',
      topRecommendation: 'Top Recommendation',
      noRecommendation: 'No executable recommendation yet. Run analysis first.',
      recommendationOutcome: 'Expected outcome',
      recommendationConfidence: 'Confidence',
      recommendationImpact: 'Impact',
      recommendationHumanReview: 'Human review required',
      recommendationReady: 'Ready for execution preview',
      whyTitle: 'Why this action?',
      whyFinding: 'Finding',
      whyEvidence: 'Data evidence',
      whyBenchmark: 'Benchmark',
      impactTitle: 'What happens after execution?',
      impactBenefit: 'Expected benefit',
      impactFinancial: 'Financial impact',
      impactTimeline: 'Timeline',
      stepsTitle: 'Execution steps',
      riskTitle: 'Risk control',
      stopLoss: 'Stop-loss',
      rollbackPlan: 'Rollback plan',
    },
    analysisSummary: { title: 'Fusion Analysis Summary', description: 'Agent A/B/C merged signal output with execution-safe recommendation scoring.', sourceLabels: { mock: 'MOCK', live: 'LIVE', fallback: 'FALLBACK' }, fallbackWarning: 'Live analysis unavailable, showing mock recommendations.' },
    recommendation: { executePreview: 'Execute Preview', details: 'Details', hide: 'Hide', urgency: 'Urgency', feasibility: 'Feasibility', confidence: 'Confidence', expectedOutcome: 'Expected Outcome', highRiskNotice: 'High-risk action should require manager confirmation before enabling auto execution.', rollbackExpired: 'Expired', rollbackLabel: 'Rollback', rollbackWindow: 'Rollback window', statuses: { idle: 'idle', pending: 'pending', executing: 'executing', completed: 'completed', failed: 'failed', rolled_back: 'rolled_back' }, risk: { low: 'low risk', medium: 'medium risk', high: 'high risk' } },
    executionPreview: { title: 'Execution Preview', rollbackAvailable: 'Rollback available', slideLabel: 'Slide to execute recommendation', slideConfirm: 'Execution requested', cancel: 'Cancel', errorFallback: 'Execution failed' },
    executionLogs: { title: 'Execution Logs', empty: 'No executions yet. Run analysis and execute a recommendation to populate logs.' },
    analysisPage: { title: 'Analysis Center', description: 'Fuse Agent A/B/C signals, rank recommendations, preview execution, and apply guarded actions with swipe confirmation.', badge: 'Interactive', hideInputPanel: 'Hide Input Panel', showInputPanel: 'Show Input Panel', inputTitle: 'Analysis Input Panel', inputDescription: 'Restaurant profile + source status. Run analysis to refresh recommendations.', runAnalysis: 'Run Analysis', runningAnalysis: 'Running…', analysisDoneToast: 'Analysis run completed.', fieldCuisine: 'Cuisine', fieldLocation: 'City', fieldCapacity: 'Capacity', fieldPriceBand: 'Price band', fieldHours: 'Hours', agentSources: 'Agent Sources', sortTitle: 'Recommendations', sortDesc: 'Sort by impact, urgency, or blended score.', sortComposite: 'Composite', sortImpact: 'Impact', sortUrgency: 'Urgency', noRecommendations: 'No recommendations yet. Adjust inputs and run analysis.', executeToastPrefix: 'Execution requested: ', rollbackToastPrefix: 'Rollback submitted: ' },
    swipe: { defaultLabel: 'Slide to confirm execution', defaultConfirm: 'Confirmed', submitting: 'Submitting…', aria: 'Swipe to confirm' },
    settingsPage: { title: 'Settings', description: 'Manage restaurant profile, agent toggles, execution policy, model routing, and integration health checks.', badge: 'Persisted locally', restoreDefaults: 'Restore Defaults', saveAll: 'Save All', savingAll: 'Saving…', saveToast: 'Settings saved.', restoreToast: 'Restored default settings.', testedToastPrefix: 'Tested ' },
    settings: {
      restaurantProfile: 'Restaurant Profile', saveProfile: 'Save profile', profileSaved: 'Restaurant profile saved.',
      fields: { restaurantName: 'Restaurant name', cuisine: 'Cuisine type', address: 'Address', city: 'City', zip: 'ZIP', capacity: 'Capacity (seats)', priceBand: 'Price band', hours: 'Hours (JSON/text)' },
      agentPanel: { title: 'Agent Toggles & Refresh Strategy', refreshFrequency: 'Refresh frequency', severityThreshold: 'Severity alert threshold', agentA: 'Agent A · Operations Data', agentB: 'Agent B · Reviews & Social', agentC: 'Agent C · Macro Factors', agentDesc: 'Enable signal ingestion and scoring for this agent.' },
      executionPolicy: { title: 'Execution Policy', allowAutoExecution: 'Allow auto execution', allowAutoExecutionDesc: 'Default off. Enables low-risk automated actions.', requireSecondConfirm: 'Require 2nd confirm for high risk', requireSecondConfirmDesc: 'Adds manager confirmation before high-risk tasks.', rollbackWindow: 'Rollback window', maxPriceAdjustment: 'Max price adjustment (%)', blacklistCategories: 'Blacklist categories' },
      modelRouting: { title: 'Model Routing', simpleTasks: 'Simple tasks', analysisTasks: 'Analysis tasks', criticalDecisions: 'Critical decisions', tokenBudget: 'Daily token budget', estimatedCost: 'Cost estimate (mock)', preset: 'Preset', optimizationMode: 'Optimization mode', qualityFirst: 'Quality First', costFirst: 'Cost First', presetCost: 'Cost priority', presetQuality: 'Quality priority' },
      integrationStatus: { title: 'Integration Status', setupGuideTitle: 'Integration Setup Guide', lastTested: 'Last tested', never: 'never', statuses: { connected: 'connected', missing: 'missing', error: 'error' } }
    },
    accountPage: { title: 'Account', description: 'Subscription, organization details, team roles, and API configuration status.', badge: 'Workspace', mockBadge: 'Mock', mockDescription: 'Mock mode account view. Placeholder data is shown while auth is disabled.', currentUser: 'Current User' },
    account: { subscription: 'Subscription', currentPlan: 'Current plan', upgrade: 'Upgrade', upgradeToast: 'Mock upgrade flow: connect billing later.', teamMembers: 'Team Members', teamDesc: 'Invite managers and staff with role-based access (mock flow).', inviteMember: 'Invite Member', inviteTitle: 'Invite Team Member', sendInvite: 'Send Invite', inviteSentPrefix: 'Invite sent to ', orgTitle: 'Organization', orgName: 'Organization Name', role: 'Role', rolePlaceholder: 'Owner', roleLabels: { Owner: 'Owner', Manager: 'Manager', Staff: 'Staff' }, demoUser: 'Demo User', orgFootnote: 'Member permissions panel is a placeholder for future org-level RBAC.', securityTitle: 'Security & API Configuration Status', securityNote: 'Never store secrets in frontend code. Server-only keys belong in .env.local and must be used only by route handlers.', configured: 'Configured', missing: 'Missing', subscriptionStats: { plan: 'Plan', analysisUsage: 'Analysis usage', executionUsage: 'Execution usage' }, memberStatus: { active: 'active', invited: 'invited' }, mockUpgradeToast: 'Mock upgrade flow.' },
    forms: { validationRequired: 'Required', validationEmail: 'Invalid email', inviteName: 'Name', inviteEmail: 'Email', inviteRole: 'Role' },
    billingAccess: {
      title: 'Billing / Access Control Demo',
      authDisabledTitle: 'Auth Disabled',
      authDisabledBody: 'Clerk auth is disabled in this environment, so pricing access checks are inactive.',
      description: 'Demonstrates Clerk Plans & Features gating with both `auth().has()` and `<Protect />`.',
      planCheck: 'Server Check: Plan (auth().has)',
      featureCheck: 'Server Check: Feature (auth().has)',
      hasPro: 'has pro',
      noPro: 'no pro',
      featureOn: 'feature on',
      featureOff: 'feature off',
      proGranted: 'This user can access Pro-only content.',
      proDenied: 'This user cannot access Pro-only content yet.',
      socialReplyGranted: 'AI social reply feature is enabled for this organization.',
      socialReplyDenied: 'AI social reply feature is not granted yet.',
      proFallbackTitle: '<Protect plan="pro" /> Fallback',
      proFallbackBody: 'Only organizations on the Pro plan can see the protected Pro module.',
      proProtectedTitle: 'Pro Plan Protected Module',
      proProtectedBody: 'Visible only when Clerk grants `plan=pro`.',
      featureFallbackTitle: '<Protect feature="social_ai_reply" /> Fallback',
      featureFallbackBody: 'Enable the `social_ai_reply` feature in Clerk Billing to unlock AI social reply workflows.',
      featureProtectedTitle: 'Feature-Protected Module: Social AI Reply',
      featureProtectedBody: 'This block demonstrates feature gating for your Social Media Radar AI reply capability.'
    }
  }
} as const;