from __future__ import annotations

from app.models.agent_config import AgentConfig, AgentRole, PipelineConfig


def build_default_pipeline(restaurant_id: str = 'default-restaurant') -> PipelineConfig:
    agents = [
        AgentConfig(
            agent_id='ops',
            name='运营数据采集',
            name_en='collector_ops',
            description='POS / 外卖 / 手动上传运营数据采集与清洗',
            role=AgentRole.COLLECTOR,
            agent_type='collector_ops',
            icon='📊',
            schedule_cron='*/15 * * * *',
            tools=[],
        ),
        AgentConfig(
            agent_id='social',
            name='社媒数据监控',
            name_en='collector_social',
            description='社媒互动、评论和提及采集',
            role=AgentRole.COLLECTOR,
            agent_type='collector_social',
            icon='📣',
            schedule_cron='0 */4 * * *',
            tools=[],
        ),
        AgentConfig(
            agent_id='macro',
            name='宏观因子采集',
            name_en='collector_macro',
            description='天气、事件、新闻等外部因子采集',
            role=AgentRole.COLLECTOR,
            agent_type='collector_macro',
            icon='🌦️',
            schedule_cron='0 */6 * * *',
            tools=[],
        ),
        AgentConfig(
            agent_id='fusion',
            name='融合分析引擎',
            name_en='analyzer_fusion',
            description='整合 A/B/C 结果并输出结构化分析摘要、KPI、异常和建议',
            role=AgentRole.ANALYZER,
            agent_type='analyzer_fusion',
            icon='🧠',
            prompt_template='analyzer.j2',
        ),
        AgentConfig(
            agent_id='planner',
            name='策略规划器',
            name_en='planner_strategy',
            description='将融合分析转换为 14 天执行计划、实验与数据请求',
            role=AgentRole.ANALYZER,
            agent_type='planner_strategy',
            icon='🗺️',
            model='gpt-4o',
            temperature=0.15,
            max_tokens=8000,
            prompt_template='planner_strategy.j2',
        ),
        AgentConfig(
            agent_id='validator',
            name='QA 校验器',
            name_en='validator_output',
            description='校验计划并生成前端可直接渲染的输出',
            role=AgentRole.ANALYZER,
            agent_type='validator_output',
            icon='🛡️',
            model='gpt-4o',
            temperature=0.0,
            top_p=1.0,
            max_tokens=6000,
            prompt_template='validator_output.j2',
        ),
        AgentConfig(
            agent_id='exec_price',
            name='动态定价执行',
            name_en='exec_pricing',
            description='价格类动作执行预览',
            role=AgentRole.EXECUTOR,
            agent_type='exec_pricing',
            icon='💲',
        ),
        AgentConfig(
            agent_id='exec_mkt',
            name='营销活动执行',
            name_en='exec_marketing',
            description='营销类动作执行预览',
            role=AgentRole.EXECUTOR,
            agent_type='exec_marketing',
            icon='🎯',
        ),
        AgentConfig(
            agent_id='exec_social',
            name='社媒发布执行',
            name_en='exec_social',
            description='社媒内容执行预览',
            role=AgentRole.EXECUTOR,
            agent_type='exec_social',
            icon='📱',
        ),
        AgentConfig(
            agent_id='exec_review',
            name='评论回复执行',
            name_en='exec_reviews',
            description='评论回复执行预览',
            role=AgentRole.EXECUTOR,
            agent_type='exec_reviews',
            icon='💬',
        ),
    ]
    edges = [
        ('ops', 'fusion'),
        ('social', 'fusion'),
        ('macro', 'fusion'),
        ('fusion', 'planner'),
        ('fusion', 'validator'),
        ('planner', 'validator'),
        ('validator', 'exec_price'),
        ('validator', 'exec_mkt'),
        ('validator', 'exec_social'),
        ('validator', 'exec_review'),
    ]
    return PipelineConfig(
        pipeline_id='default_v3',
        name='RestaurantIQ 标准运营管道',
        description='默认 A/B/C -> Fusion -> Planner -> Validator -> Executors DAG',
        restaurant_id=restaurant_id,
        agents=agents,
        edges=edges,
        global_config={'human_in_the_loop': True, 'rollback_window_minutes': 5},
        is_active=True,
    )
